use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  freeze_A: False
  mode: standalone
  client_num: 3
  total_round_num: 1000
  save_to: "fedsa-lora_mnli-m.ckpt"
  share_local_model: True
  online_aggr: False
personalization: 
  local_param: ['lora_B', 'classifier']
data:
  root: data/
  type: 'mnli@glue'
  matched: True
  splitter: 'lda'
  splits: [0.8, 0.1, 0.1]
  splitter_args: [{'alpha': 0.5}]
llm:
  tok_len: 128
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05 } ]
dataloader:
  batch_size: 128
model:
  type: 'FacebookAI/roberta-large@huggingface_llm'
train:
  local_update_steps: 10
  batch_or_epoch: batch
  optimizer:
    lr: 2e-2
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: gluetrainer
eval:
  freq: 1
  metrics: ['accuracy']
  count_flops: False
  best_res_update_round_wise_key: 'val_accuracy'
wandb:
  use: True
  name_user: 'mahi97'
  name_project: 'gaudi-fs'
  online_track: True
  client_train_info: True