use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 3
  total_round_num: 1000
  save_to: "fedsa-lora_mnli-m.ckpt"
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'mnli@glue'
  splitter: 'lda'
  splitter_args: [{'alpha': 0.5}]
  splits: [0.7, 0.15, 0.15]
  server_holds_all: False
  consistent_label_distribution: True
llm:
  tok_len: 128
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05 } ]
dataloader:
  batch_size: 128
  drop_last: False
  shuffle: True
  num_workers: 0
model:
  type: 'FacebookAI/roberta-large@huggingface_llm'
train:
  local_update_steps: 10
  batch_or_epoch: batch
  optimizer:
    lr: 2e-2
criterion:
  type: CrossEntropyLoss
trainer:
  type: gluetrainer
eval:
  freq: 1
  metrics: ['accuracy']
  count_flops: False
  best_res_update_round_wise_key: 'val_accuracy'
  split: ['train', 'val', 'test']
  report: ['weighted_avg', 'avg', 'raw']
wandb:
  use: True
  name_user: 'mahi97'
  name_project: 'gaudi-fs'
  online_track: True
  client_train_info: True