use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  freeze_A: False
  mode: standalone
  client_num: 3
  total_round_num: 1000
  save_to: "fedsa-lora_mnli-m.ckpt"
  share_local_model: True
  online_aggr: False
personalization: 
  local_param: ['lora_B', 'classifier']
data:
  root: data/
  type: 'mnli@glue'
  matched: True
  splitter: 'lda'
  splitter_args: [{'alpha': 0.5}]
llm:
  tok_len: 128
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05 } ]
dataloader:
  batch_size: 128
model:
  type: 'FacebookAI/roberta-large@huggingface_llm'
train:
  local_update_steps: 10
  batch_or_epoch: batch
  optimizer:
    lr: 2e-2
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: gluetrainer
eval:
  freq: 1
  metrics: ['accuracy']
  count_flops: False
  best_res_update_round_wise_key: 'val_accuracy'

# wandb.use 	(bool) False 	Whether to use wandb to track and visualize the FL dynamics and results. 	If False, all the related configurations (wandb.xxx) would not take effect.
# wandb.name_user 	(str) '' 	the user name used in wandb management 	-
# wandb.name_project 	(str) '' 	the project name used in wandb management 	-
# wandb.online_track 	(bool) True 	whether to track the results in an online manner, i.e., log results at every evaluation round 	-
# wandb.client_train_info 	(bool) True 	whether to track the training info of clients 	-
wandb:
  use: True
  name_user: 'mahi97'
  name_project: 'gaudi-fs'
  online_track: True
  client_train_info: True